openapi: 3.0.0

info:
    title: Let's Learn Adonis 5 API
    version: 1.0.0

servers:
    - url: http://localhost:3333/api/v1

components:
    securitySchemes:
        bearerAuth:
            type: http
            scheme: bearer
            bearerFormat: token

tags:
    - name: users
      description: User management
    - name: api-tokens
      description: API token management

paths:
    /users:
        $ref: ./resources/v1/users-collection.yaml
    /users/{user}:
        $ref: ./resources/v1/users-resource.yaml
    /api-tokens:
        $ref: ./resources/v1/api-tokens-collection.yaml
    /api-tokens/{token}:
        $ref: ./resources/v1/api-tokens-resource.yaml
